# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Graph-splined
version:      0.021
version_from: lib/GD/Graph/splined.pm
installdirs:  site
requires:
    GD:                            2.18
    GD::Graph:                     1.35
    GD::Polyline:                  0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
